# Generated by Django 4.1.5 on 2023-01-19 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='User',
            new_name='user',
        ),
    ]
