# Generated by Django 4.1.5 on 2023-01-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_email_alter_account_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
