# Generated by Django 4.1.5 on 2023-01-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.IntegerField(blank=True, default=None,null=True),
        ),
    ]
