# Generated by Django 4.1.5 on 2023-01-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
